name: shifts
description: Application for slunecni domov o.p.s. to track shifts.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  table_calendar: ^3.1.1
  package_info_plus: ^7.0.0
  shared_preferences: ^2.2.3

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#1a73b8"
  android_12:
    color: "#1a73b8"